### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by qwek1** [hlysine/create_connected#13]
[crash-2024-01-03_01.28.44-fml.txt](https://github.com/hlysine/create_connected/files/13815039/crash-2024-01-03_01.28.44-fml.txt)

**Comment by hlysine** [comment]
I'll need more info to find out the cause. 

- When did the crash happen? Is it on your very first launch after installing the mod?
- Did you modify any mod configs before this crash? Especially the block stress values for C:Connected components?

**Comment by qwek1** [comment]
nothing is modfied, and this was after a few times of launching the game. on my modpack latest version, https://www.curseforge.com/minecraft/modpacks/aoc

**Comment by hlysine** [comment]
I've downloaded your modpack and played around with it but I still haven't managed to trigger the bug. Is it a persistent bug or does it happen on occasion?

**Comment by qwek1** [comment]
The Modpack no longer has the Mod iirc, it does happen on occasion only and relaunching "fixes" it

**Comment by hlysine** [comment]
[latest.log](https://github.com/hlysine/create_connected/files/14000045/latest.log)
https://mclo.gs/J3OTlg2

Crash successfully reproduced, investigating.

**Comment by hlysine** [comment]
The crash seems to be caused by concurrency issues when C:Connected is trying to register configs for stress values. Not sure why Create is running fine when it uses the exact same piece of code to register block stress. Anyway, I've made some changes in that area in v0.6 and the issue should hopefully be fixed.
