### ISSUE TITLE
Crash loading 0.4.1

### ISSUE THREAD

**Issue by BookerCatch** [hlysine/create_connected#16]
Game does not load.
[latest.log](https://github.com/hlysine/create_connected/files/13904906/latest.log)

**Comment by hlysine** [comment]
Can you test if this issue still happens if ModernFix is removed?

**Comment by PinkLasagna03** [comment]
Also having this issue sadly, with 0.4.1. Downgrading to 0.3.1 till fixed:)

[latest.log](https://github.com/hlysine/create_connected/files/13905244/latest.log)
[crash-2024-01-11_16.35.17-client.txt](https://github.com/hlysine/create_connected/files/13905245/crash-2024-01-11_16.35.17-client.txt)

**Comment by hlysine** [comment]
[UNZIP create_connected-0.4.1-dev-mc1.20.1.zip](https://github.com/hlysine/create_connected/files/13905360/UNZIP.create_connected-0.4.1-dev-mc1.20.1.zip)

I can't reproduce this crash in my setups, but I have a theory on what's happening. Can you test if this dev version fixes your issue?

**Comment by CodexArchive** [comment]
I just updated to 0.4.1 for a 1.20.1 pack I'm working on, and I'm also getting a crash on startup. Hope this data helps narrow down the cause.

[latest.log](https://github.com/hlysine/create_connected/files/13905928/latest.log)

[crash-2024-01-11_11.32.00-client.txt](https://github.com/hlysine/create_connected/files/13905933/crash-2024-01-11_11.32.00-client.txt)

**Comment by katubug** [comment]
> [UNZIP create_connected-0.4.1-dev-mc1.20.1.zip](https://github.com/hlysine/create_connected/files/13905360/UNZIP.create_connected-0.4.1-dev-mc1.20.1.zip)
> 
> I can't reproduce this crash in my setups, but I have a theory on what's happening. Can you test if this dev version fixes your issue?

Hi, I just tested this file and I'm still crashing, here is the report and latest.log: https://gist.github.com/katubug/f1ea6cba044946f7b4e75ccf1e6262fe

**Comment by dfontana92** [comment]
Same issue for me.

I spent about an hour (nearly 100 launches of MC) trying to narrow down the specific conflict in the modlist through binary elimination, but it does not appear to be a conflict with a specific mod. Any modlist of sufficient size appears to trigger the crash.

Removing *any* single mod from this modlist resolves the crash. 

[✔] balm-forge-1.20.1-7.2.1
[✔] blockui-1.20.1-1.0.128-BETA
[✔] collective-1.20.1-7.30
[✔] create_connected-0.4.1-mc1.20.1
[✔] create_jetpack-forge-4.2.0
[✔] create_power_loader-1.3.2-mc1.20.1
[✔] create-1.20.1-0.5.1.f
[✔] createaddition-1.20.1-1.1.1
[✔] DiagonalFences-v8.1.3-1.20.1-Forge
[✔] DiagonalWindows-v8.1.3-1.20.1-Forge
[✔] domum_ornamentum-1.20-1.0.151-BETA-universal
[✔] EasyMagic-v8.0.1-1.20.1-Forge
[✔] kotlinforforge-4.10.0-all
[✔] moonlight-1.20-2.8.81-forge
[✔] PuzzlesLib-v8.1.12-1.20.1-Forge
[✔] repurposed_structures-7.1.11+1.20.1-forge
[✔] right-click-harvest-3.2.3+1.20.1-forge
[✔] structurize-1.20.1-1.0.675-BETA
[✔] supplementaries-1.20-2.7.21
[✔] towntalk-1.20.1-1.0.1
[✔] twigs-1.20.1-3.1.0-forge
[✔] twilightforest-1.20.1-4.3.1893-universal
[✔] villagernames-1.20.1-7.3
[✔] waystones-forge-1.20-14.1.3
[✔] Xaeros_Minimap_23.9.3_Forge_1.20
[✔] XaerosWorldMap_1.37.2_Forge_1.20
[✔] YungsApi-1.20-Forge-4.0.2
[✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
[✔] YungsBetterDungeons-1.20-Forge-4.0.3
[✔] YungsBetterEndIsland-1.20-Forge-2.0.4
[✔] YungsBetterJungleTemples-1.20-Forge-2.0.4
[✔] YungsBetterMineshafts-1.20-Forge-4.0.4
[✔] YungsBetterNetherFortresses-1.20-Forge-2.0.5
[✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
[✔] YungsBetterStrongholds-1.20-Forge-4.0.3
[✔] YungsBetterWitchHuts-1.20-Forge-3.0.3
[✔] YungsBridges-1.20-Forge-4.0.3
[✔] YungsExtras-1.20-Forge-4.0.3

You can see near the top of the attached log that this is only with ~1/3 my usual list enabled. Choosing any other subset of approx. 40 mods -- as long as Create Connected is enabled -- also triggers the crash.

[Crash_Sample.txt](https://github.com/hlysine/create_connected/files/13912168/Crash_Sample.txt)

**Comment by Qian-F** [comment]
Same issue: https://mclo.gs/GJ8BVO9

**Comment by hlysine** [comment]
Thanks everyone for your reports. I think I've got the issue narrowed down now. A dev version will be available for testing in a few hours once I have time to get to it.

**Comment by Qian-F** [comment]
Great! Looking for the update for 1.19.2.

**Comment by hlysine** [comment]
Hotfix 0.4.2 released
