### ISSUE TITLE
Feature Suggestion: Cherry and Bamboo Windows on 1.20

### ISSUE THREAD

**Issue by dabomb6405** [hlysine/create_connected#18]
Considering this mod is all about quality of life stuff in Create, it's always been weird to me that Create has been on 1.20 for a while now, and yet there's been no Cherry and Bamboo windows, even though all the other woods have them. I don't know why, but this has been bothering me for a while now.

If feature requests aren't allowed here, then you can take this down no problem, I just wasn't sure where else to ask about this.

**Comment by hlysine** [comment]
Yeah, I can totally add them.

**Comment by hlysine** [comment]
Cherry and bamboo windows released in v0.5! Only available for 1.20.1 of course.
