### ISSUE TITLE
Issue with Better End and this mod with sinytra connector

### ISSUE THREAD

**Issue by ZzamZ** [hlysine/create_connected#19]
When I have this mod installed with Better End I seem to keep getting a crash and it only happens with this mod. This is only as of version 0.4.0 anything before this still works. Heres the crash below! I know it says BcLib may be the cause but this seems to be the only mod that gives BcLib a problem. 
[crash-2024-01-12_17.27.12-client.txt](https://github.com/hlysine/create_connected/files/13926761/crash-2024-01-12_17.27.12-client.txt)

**Comment by hlysine** [comment]
Can't find any obvious cause while skimming the logs, but I'll look further later. You may need to forward this to sinytra connector if it turns out to be related to it.

(ref: https://mclo.gs/HJdPd5h )

**Comment by hlysine** [comment]
Fortunately, this seems to be a case of simple incompatibility between C:Connected and BetterEnd. Please test if this dev version solves your issue:

[UNZIP ME create_connected-0.4.2-dev-mc1.20.1.zip](https://github.com/hlysine/create_connected/files/13930799/UNZIP.ME.create_connected-0.4.2-dev-mc1.20.1.zip)

Technical note: although the Linked Transmitter works with modded buttons that have correct `BlockSetType` entries, their resources are not bundled in C:Connected's jar, so a custom resource pack is required for their models to render correctly.

**Comment by nthxny** [comment]
This fixed the issue.

**Comment by ZzamZ** [comment]
Yup indeed this did fix the issue!

**Comment by hlysine** [comment]
Fixed in v0.5.0+
