### ISSUE TITLE
Copycat connected texture error.

### ISSUE THREAD

**Issue by AleriaAlexie** [hlysine/create_connected#20]
Create: Connected copycat blocks connected textures are a little off at the corner connections.
At the top, got Create copycat panels.
At the bottom, got Create: Connected copycat slabs.
![Copycat panel vs copycat slab](https://github.com/hlysine/create_connected/assets/156828976/bf8204d1-a519-4b9e-ae9e-39c76dddac20)

Tested with:
Minecraft version 1.20.1
Forge version 47.2.0
Mods:
create-1.20.1-0.5.1.f.jar
create_connected-0.4.2-mc1-20.1.jar

**Comment by hlysine** [comment]
Ah I forgot to consider diagonal connections. Will fix in the next update.

**Comment by hlysine** [comment]
Fixed in v0.5.0+
