### ISSUE TITLE
Vertical brass gearboxes drop parallel gearboxes instead

### ISSUE THREAD

**Issue by Kuverr** [hlysine/create_connected#21]
as the title says, shown in video below

https://github.com/hlysine/create_connected/assets/67389809/03595c3c-6aff-4afc-934b-68dac2d60c6b

**Comment by hlysine** [comment]
Thanks for the report. The issue has already been fixed in code. It will be released in the next update.

**Comment by hlysine** [comment]
Fixed in v0.5.0+
