### ISSUE TITLE
mod loading error, a mixin crash of sorts (0.5.1)

### ISSUE THREAD

**Issue by poly-1810** [hlysine/create_connected#23]
upon loading the game with this updated version installed, it crashes before loading and i cant quite figure out what the incompatibility nor issue is
[crash-2023-12-12_10.33.01-fml.txt](https://github.com/hlysine/create_connected/files/13990458/crash-2023-12-12_10.33.01-fml.txt)
[2024-01-19-1.log](https://github.com/hlysine/create_connected/files/13990463/2024-01-19-1.log)

**Comment by hlysine** [comment]
Your crash report is unrelated to Create: Connected because it predates the release of C:Connected 0.5.1.

Your client log is truncated, but the remaining portion shows an error caused by Essential mod, also unrelated to C:Connected.

**Comment by poly-1810** [comment]
ah, alright then, will test with 0.5.1

**Comment by poly-1810** [comment]
doesnt seem to cause issues anymore, should be good
