### ISSUE TITLE
Copycat Slab connected textures

### ISSUE THREAD

**Issue by minerguy341** [hlysine/create_connected#27]
There should be more detection for which half a copycat slab is on, and whether its facing E/W or N/S or Up/Down, or if it has another slab next to it or a slab gap.
![javaw_Q7qNr4dPNC](https://github.com/hlysine/create_connected/assets/6432990/f4454fe2-b64b-40e4-8fa1-eb7676504428)

**Comment by hlysine** [comment]
I've fixed some of the more obvious errors, but because of various limitations in the existing copycat mechanism, connected textures on copycats can never be 100% perfect. 

![image](https://github.com/hlysine/create_connected/assets/25472513/f78df616-2c92-4e44-a314-73e3cd5ede51)

**Comment by hlysine** [comment]
Fix released in 0.6
