### ISSUE TITLE
Respect stress configs for components.

### ISSUE THREAD

**Issue by ManuelVFrazao** [hlysine/create_connected#4]
Using Create's configuration files, you can add or edit the stress of the various transmission blocks, such as shafts and gearboxes.

Would it be possible to make the new blocks either respect the configured stress impact of their base counterpart, or provide a separate config to add stress to them?

For instance, the gearbox variants could use the standard gearbox's stress impact, the gearshift variant could use the standard gearshift's, etc.

For the brake, I think the clutch's value would take effect while inactive, and the sheer pin could use the shaft's.

If detecting and using the configured stress impacts of base Create's components turns out impossible, I think adding configurable stress values for each new component would work nicely.

Thank you.

**Comment by hlysine** [comment]
Good suggestion. Create provides a way for add-ons to manage the stress values of new blocks via a separate config, so I think I'll go with that.

(It never occurred to me that you can set stress values for transmission blocks... Looks like an interesting way to simulate friction)

**Comment by hlysine** [comment]
Implemented, will be available in the next release.
