### ISSUE TITLE
[Unimportant] - Crowdin Contributers link going to forbidden page

### ISSUE THREAD

**Issue by lollolcheese123** [hlysine/create_connected#41]
The link for the Crowdin Contributers leads to a forbidden page

**Comment by VladisCrafter** [comment]
Can confirm - error 403

**Comment by hlysine** [comment]
Didn't realize that the members page on Crowdin is private. That sucks because I would love to credit you guys for your work, but your Crowdin profiles don't link to GitHub, and Crowdin's GitHub integration creates all PRs using my account. Any ideas for showing translation credits properly?

**Comment by lollolcheese123** [comment]
You can try this page:
[https://crowdin.com/project/create-connected-mod/reports/top-members](https://crowdin.com/project/create-connected-mod/reports/top-members)
