### ISSUE TITLE
[Bug] Sequenced Pulse Generator Not Updating Blocks

### ISSUE THREAD

**Issue by Enderkitty2001** [hlysine/create_connected#42]
When the sequence pulse generator changes its output strength, it does not update the block in front of it during its sequence 
causing to odd behavior in redstone (Apologies For High FoV Screenshot)
![image](https://github.com/hlysine/create_connected/assets/95162305/74806b2c-55df-4cdf-965c-75c9d14d8ec9)
![2024-02-04_13 23 33](https://github.com/hlysine/create_connected/assets/95162305/d7ac9eb3-e21f-4413-b407-0e1f5703baf3)

**Comment by hlysine** [comment]
This is due to the SPG incorrectly updating itself rather than the block in front when signal strength changes. Will be fixed in the next update.
