### ISSUE TITLE
Encased Chain Cogwheels unable to transfer rotation to other Encased Chain Cogwheels in different array

### ISSUE THREAD

**Issue by theTaeco** [hlysine/create_connected#52]
https://github.com/hlysine/create_connected/assets/162071649/b181e371-d8fe-4614-bd25-0ede0471dddb

Yeah, so if there are two encased chain cogwheels in different "lines" they can't transfer power to each other.

**Comment by hlysine** [comment]
This is fixed in the newest release 0.7.3
