### ISSUE TITLE
Horizontal Tanks

### ISSUE THREAD

**Issue by ItzDogo** [hlysine/create_connected#54]
Hello, I have a suggestions. Just like you did with the item vaults, could you make the tanks Horizontal please? It will make trains carrying Liquids alot shorter thanks :D

**Comment by hlysine** [comment]
I am well aware that this is a **very** highly requested feature. It is planned but please be patient while I finish some other work before getting to this.

**Comment by hlysine** [comment]
Now available in Create: Connected v0.8!
