### ISSUE TITLE
Vertical Brass Gearboxes have broken connected textures on North + East sides

### ISSUE THREAD

**Issue by goldrat1** [hlysine/create_connected#55]
Textures on the Vertical Brass Gearboxes have incorrectly connected textures on the Brass Casing sides on the North and East sides of the block. See below for example.

![2024-03-17_19 58 07](https://github.com/hlysine/create_connected/assets/45552594/01695807-c798-45a7-80ab-5dbd5c93b45d)

**Comment by hlysine** [comment]
Did not expect uv rotations to be this difficult to fix, but it's now fixed in 0.7.4
