### ISSUE TITLE
Item Silo on moving contraption voids items

### ISSUE THREAD

**Issue by Derpford** [hlysine/create_connected#57]
I put together an Item Silo with drills and a pulley to drill an elevator shaft, and it voided all of the drops. Furthermore, when I inserted items into the Item Silo via an Inventory Interface, it voided the items. 

This issue was not seen on non-contraption Silos.

Needless to say, this is kind of a big deal. I don't *think* this is a mod conflict, but I'm attaching my latest.log, which should have a full mod list in it, just in case.
[latest.log](https://github.com/hlysine/create_connected/files/14670658/latest.log)

**Comment by hlysine** [comment]
Thanks for the report. I've done some testing and found that the silo is voiding items while being disassembled. Will get this fixed asap.

**Comment by hlysine** [comment]
Hotfix 0.7.4 has been released with the fix.

**Comment by Derpford** [comment]
Just tested it on my end, and it's fixed! Be advised, though, looks like CurseForge still installs the previous version of the mod by default. IDK if that's just CF having a review process or a setting you need to poke, though.

**Comment by hlysine** [comment]
CF probably just needs more time. Everything served on CF is cached and doesn't update immediately.
