### ISSUE TITLE
Can makes compatible with Valkyrien Skies (Forge/Fabric

### ISSUE THREAD

**Issue by DrThraxGLA** [hlysine/create_connected#61]
Someone told me that they removing this mod to make Valkyrien Skies (Forge/Fabric) work is possible to make it compatible with Valkyrien Skies (Forge/Fabric) because really love this mod and don't want removing it as want Valkyrien Skies (Forge/Fabric) with clockwork so can add create tracks when out for 1.20.1

**Comment by hlysine** [comment]
I don't plan to support VS/clockwork because that mod is closed source. I think kinetic and redstone components should work fine without explicit support from my end, but contraption-related features will have to depend on luck.
