### ISSUE TITLE
[CRASH] Crash Potentially Caused by Connected

### ISSUE THREAD

**Issue by Camawama** [hlysine/create_connected#64]
While messing around with a Redstone Resistor from Clockwork x Valkyrien skies, the server is crashing quite a lot.  Using the Redstone Resistor by itself didn't seem to cause any issues and the same story with blocks from Create Connected. Once I incorporated both of them into one circuit, I was getting very frequent server crashes. It took me quite a while to figure out the exact cause but I have created the most simple circuit that can crash the server (images below).

Steps to reproduce:
1. Install Clockwork, Create: Connected, and all dependencies
2 Create a similar circuit to the image below
3. Experience crash

Minecraft: 1.20.1
Forge: 47.2.30
Create Connected: 0.7.4
Create: 0.5.1.f
Clockwork: 0.1.16-forge-b3b22e39fe

![create crash woohoo](https://github.com/hlysine/create_connected/assets/43620900/06d8e9dd-6662-40ba-bec0-e715cd3e0122)
[latest.log](https://github.com/hlysine/create_connected/files/15461866/latest.log)
[crash-2024-05-27_21.18.07-server.txt](https://github.com/hlysine/create_connected/files/15461867/crash-2024-05-27_21.18.07-server.txt)

**Comment by Camawama** [comment]
The issue is non deterministic and it appears to happen depending on the block that the create stress system breaks. Either the server crashes or a block breaks.

**Comment by hlysine** [comment]
Issue is unrelated to Create: Connected because it can be reproduced using Create's clutch and gearshift, without Create: Connected installed.
