### ISSUE TITLE
Fan freezing catalyst does not work

### ISSUE THREAD

**Issue by shawnbucholtz** [hlysine/create_connected#68]
I have a custom modpack with _Create: Connected_ and _Create: Dreams & Desires_

When I use a freezing catalyst it does not freeze anything; nor does it have the mechanics from DD which causes slowness.  All other catalysts I've used work fine (and with custom recipes). It is mentioned on Curse forge:

> A new catalyst for bulk freezing. Works with Create: Garnished and Create: Dreams & Desires.

So I assumed it would work.

Further, the logs don't have any indication of it being an error. Attached for reference:

[latest.log](https://github.com/user-attachments/files/15796163/latest.log)

In-game there is a visible difference:

![2024-06-11_18 30 42](https://github.com/hlysine/create_connected/assets/60205912/730aeb24-c989-4a39-8349-c863b5778966)

**Comment by hlysine** [comment]
This is due to the catalyst having tags from the older version of C:DnD. It will be fixed in the next update.
