### ISSUE TITLE
Ideas for Control Chip redesigns

### ISSUE THREAD

**Issue by LunarAnticGitHub** [hlysine/create_connected#69]
![incomplete_control_chip](https://github.com/hlysine/create_connected/assets/131813123/fc52ed6d-1980-42a4-a9cb-f27395dfef75)
![control_chip](https://github.com/hlysine/create_connected/assets/131813123/ea44a91f-8dd3-4b7b-bf3a-908768bbecae)

The incomplete control chip has an Electron Tube, redstone and some cogs in it, thought it would add more detail. I had them both upsized to 32x32 so the tabs would be equalized

**Comment by hlysine** [comment]
They look awesome! I'll put them in the next update and give you credit for it. Thanks for helping!
