### ISSUE TITLE
Failed to load without JEI

### ISSUE THREAD

**Issue by Kuverr** [hlysine/create_connected#7]
![image](https://github.com/hlysine/create_connected/assets/67389809/84c8c124-9066-4ebc-a168-5e0dacae130f)

as the title says, mod fails to load when JustEnoughItems is not installed

[crash-2023-12-26_10.57.56-fml.txt](https://github.com/hlysine/create_connected/files/13770629/crash-2023-12-26_10.57.56-fml.txt)

**Comment by hlysine** [comment]
Code related to JEI was put in the wrong place, now fixed.
