### ISSUE TITLE
Failing mixin in 0.9.1

### ISSUE THREAD

**Issue by evanfoster** [hlysine/create_connected#80]
Hey there!

My server (I'm using [this Helm chart](https://github.com/itzg/minecraft-server-charts/tree/master/charts/minecraft) to run my server and handle mods) automagically updated Create: Connected to 0.9.1 because I am a silly goose who forgot to pin my mod versions. When this happened, my server started crashlooping. I initially followed the auto-generated Forge link and found [this thread](https://github.com/Creators-of-Create/Create/issues/6950), but the issue appears to be a small oops in Create: Connected related to mixins.

Here's a crash report: [crash-2024-09-20_00.21.10-fml.txt](https://mclo.gs/81pDFsA)
Here's the `latest.log`: [latest.log](https://gist.github.com/evanfoster/e237f39489b0e95d50108449a546c65a#file-latest-log)

The timestamps on those two won't line up because my server is running in k8s and was in crashloopbackoff. 

Downgrading Create: Connected to 0.9.0 (`HlCC58dD` on Modrinth) resolved the issue.

**Comment by hlysine** [comment]
Create: Connected 0.9.1 is currently incompatible with Create 0.5.1f or below. Please upgrade Create to 0.5.1g or downgrade Connected to 0.9.0 for now.

**Comment by evanfoster** [comment]
🤦 my bad, I should have done my homework. Apologies for the erroneous report, I'll go ahead and close this.
