### ISSUE TITLE
Horizontal Fluid Tanks

### ISSUE THREAD

**Issue by okunamayanad** [hlysine/create_connected#81]
Much like the vertical item silos, I think having horizontal fluid tanks would be incredibly useful. For example, I'm currently building a car using Clockwork and making a motor for the car using The Factory Must Grow. I need to store gasoline somewhere and, much like the real cars, I decided to store it under the vehicle but there's no horizontal fluid tank so I can't.

**Comment by hlysine** [comment]
Horizontal fluid tanks are already here! They are called fluid vessels in the mod.

**Comment by okunamayanad** [comment]
> Horizontal fluid tanks are already here! They are called fluid vessels in the mod.

Can't believe I missed it! I guess because I searched for tank instead of fluid and because they're not on any picture on Modrinth. Sorry, my bad
