### ISSUE TITLE
Crashes the game when going into inventory

### ISSUE THREAD

**Issue by CrSimple-d** [hlysine/create_connected#87]
Tried it on the server

Logs: [latest.log](https://github.com/user-attachments/files/17964399/latest.log)

Crash-report: [crash-2024-11-29_20.35.39-client.txt](https://github.com/user-attachments/files/17964393/crash-2024-11-29_20.35.39-client.txt)

**Comment by hlysine** [comment]
This crash is caused by Create: Interactive. Please report your crash on their issue tracker instead.

**Comment by CrSimple-d** [comment]
I removed create: connected without deleting create: interactive and the inventory started working in creative mode. Could this be a mod conflict?

**Comment by hlysine** [comment]
Are you using official releases of Create: Interactive and Create: Connected? There are some weird lines in the crash report which may indicate that your mod jars are modified.

Even if this is a mod conflict, I will not be supporting Create: Interactive since the mod is closed source.
