### ISSUE TITLE
Encased Chain Cogwheel render error

### ISSUE THREAD

**Issue by Revv1e** [hlysine/create_connected#90]
In version **create_connected 0.8.2-mc1.18.2** the Encased Chain Cogwheel blocks seem to have a weird sort of Z Fighting happening 
![image](https://github.com/user-attachments/assets/6fc19f65-b513-4f83-98e3-cdd487ac23e5)
![image](https://github.com/user-attachments/assets/9104193c-4a22-4883-90f8-9734ee29918d)
![image](https://github.com/user-attachments/assets/5f16e913-518d-417a-b78d-2d4032301961)

It's quite subtle in the images, but imagine this flickering, it almost feels like it doesn't know whether or not it should be allowing light to pass through it or not?

It may be due to some dynamic lighting colliding with its rendering, but I am unsure.

**Comment by hlysine** [comment]
Are you using Create: Extended Cogwheels? This looks similar to #10

**Comment by Revv1e** [comment]
Yes I do have it, seems like those two mods dont mesh well?

**Comment by hlysine** [comment]
Create: Extended Cogwheels is incompatible with several other mods which add kinetic components, including Create: Connected and Petrol's Parts. It is an issue on their end (https://github.com/Rabbitminers/Extended-Cogwheels/issues/83) but the mod seems to be inactive unfortunately.

**Comment by Alastors** [comment]
Fixed on my end, I'm kicking out a few more targeted patches and I'll send it out on the unofficial branch before updating it to 6.0.0

Sorry the original dev never fixed it though.
